package konten;
import javax.swing.JOptionPane;
import User_View.Login;
import java.awt.CardLayout;

public class petugas extends javax.swing.JFrame {

 CardLayout cardLayout;
    public petugas() {
        setTitle("Petugas/Admin");
        initComponents();
        setLocationRelativeTo(null);
        konten.add(Verifikasi, "Verifikasi");
        konten.add(Tanggapan, "Tanggapan");
        konten.add(RegisPetugas, "RegisPetugas");
        konten.add(RegisUser, "Regisuser");
        konten.add(LihatLaporan, "LihatLaporan");
       cardLayout = (CardLayout)(konten.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        verifikasi = new javax.swing.JLabel();
        lihatlaporan = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        tanggapan = new javax.swing.JLabel();
        regispetugas = new javax.swing.JLabel();
        regisuser = new javax.swing.JLabel();
        konten = new javax.swing.JPanel();
        Verifikasi = new javax.swing.JPanel();
        Tanggapan = new javax.swing.JPanel();
        RegisPetugas = new javax.swing.JPanel();
        RegisUser = new javax.swing.JPanel();
        LihatLaporan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(234, 253, 252));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/Logo.png"))); // NOI18N

        verifikasi.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        verifikasi.setForeground(new java.awt.Color(102, 102, 102));
        verifikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/Verifikasi_Laporan.png"))); // NOI18N
        verifikasi.setText("  Verifikasi ");
        verifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verifikasiMouseClicked(evt);
            }
        });

        lihatlaporan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lihatlaporan.setForeground(new java.awt.Color(102, 102, 102));
        lihatlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/Lihat_Laporan.png"))); // NOI18N
        lihatlaporan.setText("Lihat Laporan");
        lihatlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lihatlaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatlaporanMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 51, 51));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        tanggapan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tanggapan.setForeground(new java.awt.Color(102, 102, 102));
        tanggapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/Buat_Tanggapan.png"))); // NOI18N
        tanggapan.setText("  Tanggapan");
        tanggapan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tanggapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggapanMouseClicked(evt);
            }
        });

        regispetugas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        regispetugas.setForeground(new java.awt.Color(102, 102, 102));
        regispetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/regis_petugas.png"))); // NOI18N
        regispetugas.setText("Regis Petugas");
        regispetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regispetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regispetugasMouseClicked(evt);
            }
        });

        regisuser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        regisuser.setForeground(new java.awt.Color(102, 102, 102));
        regisuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawable/regis_user.png"))); // NOI18N
        regisuser.setText("Regis User");
        regisuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisuserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(verifikasi))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tanggapan))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(regispetugas))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(regisuser))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lihatlaporan))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(logout))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(verifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tanggapan)
                .addGap(18, 18, 18)
                .addComponent(regispetugas)
                .addGap(18, 18, 18)
                .addComponent(regisuser)
                .addGap(18, 18, 18)
                .addComponent(lihatlaporan)
                .addGap(82, 82, 82)
                .addComponent(logout))
        );

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 670));

        konten.setBackground(new java.awt.Color(191, 234, 245));
        konten.setLayout(new java.awt.CardLayout());

        Verifikasi.setBackground(new java.awt.Color(191, 234, 245));

        javax.swing.GroupLayout VerifikasiLayout = new javax.swing.GroupLayout(Verifikasi);
        Verifikasi.setLayout(VerifikasiLayout);
        VerifikasiLayout.setHorizontalGroup(
            VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        VerifikasiLayout.setVerticalGroup(
            VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        konten.add(Verifikasi, "card2");

        Tanggapan.setBackground(new java.awt.Color(191, 234, 245));

        javax.swing.GroupLayout TanggapanLayout = new javax.swing.GroupLayout(Tanggapan);
        Tanggapan.setLayout(TanggapanLayout);
        TanggapanLayout.setHorizontalGroup(
            TanggapanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        TanggapanLayout.setVerticalGroup(
            TanggapanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        konten.add(Tanggapan, "card3");

        RegisPetugas.setBackground(new java.awt.Color(191, 234, 245));

        javax.swing.GroupLayout RegisPetugasLayout = new javax.swing.GroupLayout(RegisPetugas);
        RegisPetugas.setLayout(RegisPetugasLayout);
        RegisPetugasLayout.setHorizontalGroup(
            RegisPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        RegisPetugasLayout.setVerticalGroup(
            RegisPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        konten.add(RegisPetugas, "card4");

        RegisUser.setBackground(new java.awt.Color(191, 234, 245));

        javax.swing.GroupLayout RegisUserLayout = new javax.swing.GroupLayout(RegisUser);
        RegisUser.setLayout(RegisUserLayout);
        RegisUserLayout.setHorizontalGroup(
            RegisUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        RegisUserLayout.setVerticalGroup(
            RegisUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        konten.add(RegisUser, "card5");

        LihatLaporan.setBackground(new java.awt.Color(191, 234, 245));

        javax.swing.GroupLayout LihatLaporanLayout = new javax.swing.GroupLayout(LihatLaporan);
        LihatLaporan.setLayout(LihatLaporanLayout);
        LihatLaporanLayout.setHorizontalGroup(
            LihatLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        LihatLaporanLayout.setVerticalGroup(
            LihatLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        konten.add(LihatLaporan, "card6");

        getContentPane().add(konten, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            // Melakukan logout dan pindah ke jframe login
            // Code untuk melakukan logout
            dispose(); // menutup frame saat ini
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void verifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifikasiMouseClicked
        cardLayout.show(konten, "Verifikasi");
    }//GEN-LAST:event_verifikasiMouseClicked

    private void tanggapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggapanMouseClicked
        cardLayout.show(konten, "Tanggapan");
    }//GEN-LAST:event_tanggapanMouseClicked

    private void regispetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regispetugasMouseClicked
        cardLayout.show(konten, "RegisPetugas");
    }//GEN-LAST:event_regispetugasMouseClicked

    private void regisuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisuserMouseClicked
        cardLayout.show(konten, "RegisUser");
    }//GEN-LAST:event_regisuserMouseClicked

    private void lihatlaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatlaporanMouseClicked
        cardLayout.show(konten, "LihatLaporan");
    }//GEN-LAST:event_lihatlaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LihatLaporan;
    private javax.swing.JPanel RegisPetugas;
    private javax.swing.JPanel RegisUser;
    private javax.swing.JPanel Tanggapan;
    private javax.swing.JPanel Verifikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel konten;
    private javax.swing.JLabel lihatlaporan;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel regispetugas;
    private javax.swing.JLabel regisuser;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel tanggapan;
    private javax.swing.JLabel verifikasi;
    // End of variables declaration//GEN-END:variables
}
